version: "3.6"

services:
  db:
    image: docker.io/postgres:13-alpine
    container_name: ${INSTANCE_NAME}-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
  backup:
    image: docker.io/prodrigestivill/postgres-backup-local:13-alpine
    container_name: ${INSTANCE_NAME}-backup
    restart: unless-stopped
    volumes:
      - ${BACKUP_PATH}:/backups/:z
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=${BACKUP_EXTRA_OPTS}
      - POSTGRES_HOST=${BACKUP_DB_HOST}
      - POSTGRES_PORT=${BACKUP_DB_PORT}
      - SCHEDULE=${BACKUP_SCHEDULE}
  bot:
    image: ghcr.io/strawberry-py/strawberry-py:latest
    container_name: ${INSTANCE_NAME}-bot
    env_file: .env
    volumes:
      - ./:/strawberry-py/:z
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
