# .github/workflows/docker_build.yml
name: Docker Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *' # Run on the 1st and 15th day of the month
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - "**/entrypoint.sh"
      - "**/build-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      platforms: linux/amd64,linux/arm64
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
